name: Node.js CI

on:
  push:
    branches: [ Develop ]
  pull_request:
    branches: [ Develop ]
    
env:
  REGISTRY_NAME: 'kwetters6'
  CLUSTER_NAME: 'kwetters6'
  CLUSTER_RESOURCE_GROUP: 'kwetter_s6_kubernetes_resource_group'
  NAMESPACE: 'default'
  SECRET: 'githubdeploymentsecret'
  APP_NAME: 'frontend'
  APP_VERSION: 'v0.1.8'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Angular Github Actions
      uses: mayurrawte/github-angular-actions@latest
    - run: webdriver-manager update
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v1
        with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '88.0.4324.96'
    - run: |
      export DISPLAY=:99
      chromedriver --url-base=/wd/hub &
      sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - run: protractor conf.js

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         todo: add to secrets vault in github
        SONAR_TOKEN: 3f4e3bd05a233f7f2002079a770e94e89262edf2
  static_web_app_deploy_job:
    needs: [build_and_test]
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Static Web App Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_PEBBLE_0272E8B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/kwetter-front-end" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_PEBBLE_0272E8B03 }}
          action: "close"
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://ashy-pebble-0272e8b03.1.azurestaticapps.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
